region              = "ap-south-1"
instance_type       = "t2.micro"
vpc_cidr            = "10.0.0.0/16"
public_subnet_cidr  = "10.0.1.0/24"
availability_zone   = "ap-south-1a"
key_name            = "Devops-CI-CD"
ecr_repository_url  = "381492025611.dkr.ecr.ap-south-1.amazonaws.com/devops-ci-cd-project"
